version: "4.37.2 "

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: Hauzanrafi09
      POSTGRES_PASSWORD: Hauzanrafi09
      POSTGRES_DB: School_Dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL:"postgresql://Hauzanrafi09:Hauzanrafi09@localhost:5432/School_Dashboard"
    depends_on:
      - postgres

volumes:
  postgres_data:
